# Generated by Django 5.2.1 on 2025-07-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_express', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cheout_id',
            new_name='checkout_id',
        ),
    ]
