# Generated by Django 5.2.1 on 2025-07-01 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='account_reference',
            field=models.CharField(default='TAX_PAYMENT', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='description',
            field=models.CharField(default='Tax Payment', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
