# Generated by Django 5.2.1 on 2025-06-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_api', '0002_remove_user_is_vendor_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
