# Generated by Django 5.2.1 on 2025-06-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_api', '0003_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('service', 'Service Provider'), ('other', 'Other')], default='retail', max_length=20, verbose_name='business type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='national id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('vendor', 'Vendor')], default='vendor', max_length=20, verbose_name='role'),
        ),
    ]
