# Generated by Django 5.2.1 on 2025-07-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_api', '0011_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='market_of_operation',
            field=models.CharField(choices=[('kapsabet', 'Kapsabet Market'), ('mosoriot', 'Mosoriot Market'), ('nandi_hills', 'Nandi Hills Market'), ('kabiyet', 'Kabiyet Market'), ('kebulonik', 'Kebulonik Market'), ('lessos', 'Lessos Market'), ('kaiboi', 'Kaiboi Market'), ('chepterit', 'Chepterit Market'), ('baraton', 'Baraton Market'), ('kipkaren', 'Kipkaren Market')], default='kapsabet', max_length=20),
            preserve_default=False,
        ),
    ]
