# Generated by Django 5.2.1 on 2025-07-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_api', '0012_user_market_of_operation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='account_reference',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='TEMP_TXN_ID', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_date',
            field=models.DateTimeField(default='TEMP_TXN_ID'),
            preserve_default=False,
        ),
    ]
