# Generated by Django 5.2.1 on 2025-07-01 21:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_api', '0013_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
